### ISSUE TITLE
Vib-Ripple decompilation

### ISSUE THREAD

**Issue by yumnycheesecakes** [polybiusproxy/open-ribbon#26]
Will there be one?

**Comment by AnOpenSauceDev** [comment]
I'm not really associated with the project, but this does seem to be pretty dead. Not only that, but Vib-Ripple is a very different game due to how the PS2 works, so the majority of the work here probably wouldn't translate over at all.

The issue is that game decompilation is a very exhaustive and complex process (even for a game as seemingly simple as Vib-Ribbon!), so it could over a year to reverse engineer Vib-Ripple if you're unlucky.

**Comment by yumnycheesecakes** [comment]
Ah okay then. I wish someday an Vib-Ripple decompilation will exist. I still can't import images into Vib-Ripple :/

**Comment by polybiusproxy** [comment]
Hi, thanks for your interest!

A Vib-Ripple decompilation is feasible and possible, but as @AnOpenSauceDev said, it'd be a very exhaustive process, just like the current Vib-Ribbon decompilation.

In addition, both games were written in C++, which makes the process even harder.
Therefore I have, as of now, no plans on starting such a project.
